export default (ActionTypes = {
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    SET_LOGIN_STORY: 'SET_LOGIN_STORY',
    SET_USER_LOCATION: 'SET_USER_LOCATION',
    SET_REGISTERED_USERS: 'SET_REGISTERED_USERS',
});
